#pragma once

#define CAP_IMAGE_WIDTH 640
#define CAP_IMAGE_HEIGHT 480
#define SHOW_IMAGE_WIDTH 320
#define SHOW_IMAGE_HEIGHT 240


#define TEMPLATE_IMAGE_PATH "targetDB/imgcut_40.bmp"

//caution!! before you decree a new variable, check alignment!!

#define VCC_DATABASE_SIZE 9
#define VCC_TEMPLATE_SIZE 32
#define VCC_TEMPLATE_HALF_SIZE (VCC_TEMPLATE_SIZE/2)
#define VCC_TEMPLATE_QUARTER_SIZE (VCC_TEMPLATE_SIZE/4)
#define VCC_INPUT_IMAGE_SIZE_X 640
#define VCC_INPUT_IMAGE_SIZE_Y 480
#define VCC_SEEK_AREA_SIZE 128
#define VCC_SEEK_AREA_SIZE_X (VCC_SEEK_AREA_SIZE-3)
#define VCC_SEEK_AREA_HALF_SIZE ((VCC_SEEK_AREA_SIZE+1)/2)
#define VCC_VECTOR_CODE_THRESHOLD 60
#define VCC_SEEK_AREA_VECTOR_CODE_SIZE (VCC_SEEK_AREA_SIZE+1-VCC_TEMPLATE_SIZE)
#define VCC_SEEK_AREA_VECTOR_CODE_HALF_SIZE (VCC_SEEK_AREA_VECTOR_CODE_SIZE/2)
#define VCC_DISSIMILARITY_THRESHOLD 500
#define VCC_CORRELATION_THRESHOLD 2048
#define VCC_TEMPLATE_HALF_X (VCC_TEMPLATE_SIZE/2+1)
#define VCC_ALL_SEEK_THRESHOLD 800
#define VCC_SURROUND_SEEK_PIXEL 1